name: Validate App

on:
  pull_request:
    branches: ['main']
  push:
    branches: ['main']

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

jobs:
  validate:
    name: Lint and Typecheck
    runs_on: linux-medium
    steps:
      - uses: eas/checkout
      - uses: eas/install_node_modules
      - run: npm run lint
      - run: npm run typecheck
