name: Android Development Build

on:
  workflow_dispatch: {}

jobs:
  build_android_development:
    name: Build Android Dev Client
    type: build
    params:
      platform: android
      profile: development
      message: 'Manual Android development client build'
