name: Android Preview Build

on:
  workflow_dispatch: {}

jobs:
  build_android_preview:
    name: Build Android Preview APK
    type: build
    params:
      platform: android
      profile: preview
      message: 'Manual Android preview APK build'
